### ISSUE TITLE
Terima PR - Pull Request saya yaa

### ISSUE THREAD

**Issue by ipang-dwi** [mudrikul/open-CI-web#2]
Terima PR - Pull Request saya yaa. Trus, nanti akan saya update repo nya dengan beberapa file dan video yang saya buat, agar bisa dipakai teman-teman yang sedang belajar, dan memakai repo ini sebagai "base-repository" mereka. - :)

**Comment by ipang-dwi** [comment]
Jangan lupa untuk close issue ini, setelah menerima PR dari saya untuk repo ini.

**Comment by mudrikul** [comment]
oke , di acc PR nya, makasih ya kontribusi ilmunya
